(()=>{
 const form=document.querySelector('#enquiry');if(!form)return;
 const config=window.GC_ENQUIRY_CONFIG||{};const endpoint=config.enabled?config.endpoint:'';
 const button=form.querySelector('button[type="submit"]'),status=document.querySelector('#status'),summary=document.querySelector('#enquiry-errors');
 if(endpoint){button.textContent='Send enquiry';document.querySelector('#enquiry-note').textContent='Please avoid medical records, NDIS numbers or other sensitive details. Your contact details and message will be sent securely to our enquiry delivery service so Guardians Connect can respond.';document.querySelector('.contact-note').textContent='Send a service enquiry using this form. Service availability and arrangements are confirmed individually.';}
 function errors(values){const result=[];if(!values.name.trim())result.push(['name','Enter your name.']);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim()))result.push(['email','Enter a valid email address so we can respond.']);if(!values.message.trim())result.push(['message','Tell us what you would like help with.']);return result;}
 function showErrors(list){summary.replaceChildren();for(const id of ['name','email','message']){form.elements[id].removeAttribute('aria-invalid');document.querySelector('#'+id+'-error').hidden=true;}summary.hidden=!list.length;if(!list.length)return;const heading=document.createElement('p');heading.textContent='Please check the following fields:';summary.append(heading);const ul=document.createElement('ul');for(const[id,text]of list){form.elements[id].setAttribute('aria-invalid','true');const error=document.querySelector('#'+id+'-error');error.textContent=text;error.hidden=false;const li=document.createElement('li'),a=document.createElement('a');a.href='#'+id;a.textContent=text;a.addEventListener('click',e=>{e.preventDefault();form.elements[id].focus();});li.append(a);ul.append(li);}summary.append(ul);summary.focus();}
 function download(values){const text=['GUARDIANS CONNECT — ENQUIRY','Prepared: '+new Date().toLocaleDateString('en-AU'),'Name: '+values.name,'Email: '+values.email,'Phone: '+(values.phone||'Not provided'),'Support area: '+values.service,'','What I would like help with:',values.message,'','This enquiry has not been sent. Share it using confirmed Guardians Connect contact details.'].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='guardians-connect-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Your enquiry copy has been downloaded. It has not been sent to Guardians Connect.';status.focus();}
 let sending=false;
 form.addEventListener('submit',async e=>{e.preventDefault();if(sending)return;status.textContent='';const values=Object.fromEntries(new FormData(form));if(values.website){status.textContent='The enquiry could not be submitted. Please refresh and try again.';return;}const invalid=errors(values);showErrors(invalid);if(invalid.length)return;if(!endpoint){download(values);return;}
 sending=true;button.disabled=true;button.textContent='Sending…';form.setAttribute('aria-busy','true');status.textContent='Sending your enquiry. Please wait.';const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);
 try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({name:values.name,email:values.email,phone:values.phone,service:values.service,message:values.message,_subject:'Guardians Connect — website enquiry',_replyto:values.email}),signal:controller.signal});let result;try{result=await response.json();}catch{throw new Error('invalid-response');}if(/activat|confirm your email|verify your email/i.test(result.message||''))throw new Error('activation-pending');if(!response.ok||!(result.ok===true||result.success===true||result.success==='true'))throw new Error('not-confirmed');form.reset();status.textContent='Thank you. Your enquiry has been submitted successfully to Guardians Connect. We will respond using the contact details you provided.';status.focus();}
 catch(err){status.textContent=err.name==='AbortError'?'We could not confirm that your enquiry was received because the request timed out. Your entries are still here. Please try again; avoid repeated retries in case your first enquiry arrived.':'Your enquiry could not be confirmed. Your entries are still here. Please try again later.';status.focus();}
 finally{clearTimeout(timer);sending=false;button.disabled=false;button.textContent='Send enquiry';form.removeAttribute('aria-busy');}
 });
 for(const id of ['name','email','message'])form.elements[id].addEventListener('input',()=>{form.elements[id].removeAttribute('aria-invalid');document.querySelector('#'+id+'-error').hidden=true;});
})();
